# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'trailers' do
  use_frameworks!
  pod 'Alamofire'
  pod 'Freddy'

  target 'trailersTests' do
    inherit! :search_paths
    pod 'Expecta'
    pod 'OCMock'
    pod 'FBSnapshotTestCase', '~> 2.0.6'
  end

  target 'trailersUITests' do
    inherit! :search_paths
  end

end
